############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Meet the Team"
url = "/team"
weight = 2

[[main]]
weight = 3
name = "Our Research"

[[main]]
parent = "Our Research"
name = "Manuscripts"
url = "/manuscripts"

[[main]]
parent = "Our Research"
name = "Reports"
url = "/reports"

[[main]]
parent = "Our Research"
name = "See All Research"
url = "/research"

[[main]]
parent = "Pages"
name = "Blog"
url = "/blog"

[[main]]
parent = "Pages"
name = "Gallery"
url = "/gallery"

[[footer]]
name = "Meet the Team"
url = "/team"
weight = 1

[[footer]]
name = "Our Research"
url = "/research"
weight = 3

[[footer]]
name = "Photo Gallery"
url = "/gallery"
weight = 3

[[main]]
parent = "Pages"
name = "Lab News"
url = "/news"
